// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

interface IGroth16Verifier9 {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[9] calldata input
    ) external view returns (bool);
}

// Adapter for Groth16 verifiers generated by snarkjs Solidity templates.
//
// Expected `proof` encoding:
// abi.encode(uint256[2] a, uint256[2][2] b, uint256[2] c)
//
// Expected public signal length:
// 9 (aligned with selective disclosure manager signal convention).
contract Groth16VerifierAdapter {
    IGroth16Verifier9 public immutable verifier;

    error InvalidVerifierAddress();
    error InvalidPublicSignalsLength(uint256 provided);

    constructor(address verifierAddress) {
        if (verifierAddress == address(0)) {
            revert InvalidVerifierAddress();
        }
        verifier = IGroth16Verifier9(verifierAddress);
    }

    function verifyProof(
        bytes calldata proof,
        uint256[] calldata publicSignals
    ) external view returns (bool) {
        if (publicSignals.length != 9) {
            revert InvalidPublicSignalsLength(publicSignals.length);
        }

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = abi.decode(
            proof,
            (uint256[2], uint256[2][2], uint256[2])
        );

        uint256[9] memory fixedSignals;
        for (uint256 i = 0; i < 9; i++) {
            fixedSignals[i] = publicSignals[i];
        }

        return verifier.verifyProof(a, b, c, fixedSignals);
    }
}
